# Alembic configuration file
# The sqlalchemy.url is read from .env file

[alembic]
# path to migration scripts
script_location = ../migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be named with datetime instead
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to the constructor of datetime.datetime
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# set to 0 to disable
truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# if true, revision files are written as days since epoch, rounded
# to the nearest day
# dated_revisions = false

# format using python string.format() or datetime.strftime()
# string value is passed to the constructor of datetime.datetime
# "iso8601" - (new in 1.10) picks the latter format
# The default
# file_template = %%(rev)s_%%(slug)s.py

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
